apiVersion: v1
kind: Service
metadata:
  name: backup-recovery-demo-app
  namespace: backup-recovery-demo
  labels:
    app: backup-recovery-demo-app
spec:
  type: ClusterIP
  selector:
    app: backup-recovery-demo-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
