apiVersion: batch/v1
kind: Job
metadata:
  name: backup-data-job
  namespace: backup-recovery-demo
  labels:
    app: backup-recovery-demo-backup
spec:
  template:
    metadata:
      labels:
        app: backup-recovery-demo-backup
    spec:
      restartPolicy: Never
      containers:
        - name: backup
          image: alpine:3.20
          env:
            - name: BACKUP_MODE
              value: crash-consistent
            - name: APP_BASE_URL
              value: http://backup-recovery-demo-app.backup-recovery-demo.svc.cluster.local:8080
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              /scripts/backup.sh
          volumeMounts:
            - name: app-data
              mountPath: /data
            - name: backup-storage
              mountPath: /backup
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data-pvc
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-storage-pvc
        - name: scripts
          configMap:
            name: backup-restore-scripts
            defaultMode: 0755
  backoffLimit: 0
